version: "3.7"
services:
  pxe-server:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    env_file: ".env"
    container_name: pxe-server
    privileged: true
    networks:
      dockervlan:
          ipv4_address: 10.1.22.9
    volumes: 
      - ${TFTP_DIR}:/srv/tftp
      - ${NFS_DIR}:/nfs
      - ${PWD}/etc/exports:/etc/exports 
      - ${PWD}/etc/default/nfs-kernel-server:/etc/default/nfs-kernel-server 
      - ${PWD}/etc/default/isc-dhcp-server:/etc/default/isc-dhcp-server 
      - ${PWD}/etc/dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf 
      - ${PWD}/etc/network/interfaces:/etc/network/interfaces   
networks:
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts: 
       parent: br_test
    ipam:
      config:
        - subnet: "10.1.22.0/24"
          ip_range: "10.1.22.64/26"
          gateway: "10.1.22.254"
  
